### ISSUE TITLE
Error in results awaited wth the main script

### ISSUE THREAD

**Issue by E-HO** [Azure-Samples/azure-cosmos-db-mongodb-python-getting-started#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Follow the documentation, copy the code, run the main "run.py" script, provide a working connection string.

### Any log messages given by the failure
>No error shown

### Expected/desired behavior
> Following the example we should have a document created in a collection named "unsharded-sample-collection".
But the script creates another container named "COLLECTION_NAME" and put documents in this collection but not in the first correct we created. Error could be with the return of function "create_database_unsharded_collection()".

### OS and Version?
> Not relevant

### Versions
> Not relevant, latest

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by E-HO** [comment]
Possible solution, replace line "return db.COLLECTION_NAME" 
with "return db[UNSHARDED_COLLECTION_NAME]"

**Comment by vmagelo** [comment]
I think this got addressed. If not, reopen and point me to specifi location.  Thanks!
